Removed /preload + Multidisabler Update
Removed /preload to avoid issues to the end-user.
Updated Multidisabler

diff --git a/recovery/root/system/bin/multidisabler b/recovery/root/system/bin/multidisabler
--- a/recovery/root/system/bin/multidisabler
+++ b/recovery/root/system/bin/multidisabler
@@ -1,206 +1,338 @@
-#!/system/bin/sh
+#!/sbin/sh
 #
 # A simple Samsung services disabler by Ian Macdonald.
 #
 # Use this to prime your device after installing TWRP.
 
-md5() {
-  md5sum -b "$1"
-}
+   help_screen() {
+      echo "  Multidisabler v3.1 by @ianmacd  ";
+      echo "";
+      echo " - Disables FBE, Vaultkeeper, ProcA, wsm,";
+      echo "   cass, Stock recovery rewrite and patches";
+      echo "   libbluetooth for rooted devices";
+      echo "";
+      echo " - Usage : $0 <option>";
+      echo "";
+      echo " - Options:";
+      echo "    --help                        Print this help screen and quit";
+      echo ".   --all.                          Select all the options supported by the device"
+      echo "    --disable-fbe                 Disable File-based encryption by patching vendor fstab.";
+      echo "    --disable-stockrec-override  Prevent stock recovery from overriding the currently installed one";
+      echo "    --disable-vaultkeeper        Disable VaultKeeper";
+      echo "    --disable-proca              Disable Process Authentication";
+      echo "    --patch-bluetooth-lib         Patch Bluetooth lib to fix connection issues on Android 10";
+      echo "    --disable-wsm               Disable wsm"
+      echo "    --disable-cass               Disable Cass"
+      echo "Examples:";
+      echo "    $0 --all";
+      echo "    $0 --disable-fbe --disable-stockrec-override";
+      echo "";
+      exit 0;
+   }
 
-file_changed() {
-  local file="$1"
-  local old_md5="$2"
-  local new_md5=$( md5 "$file" )
+   md5() {
+     md5sum -b "$1"
+   }
 
-  if [ $new_md5 != $old_md5 ]; then
-    echo " -     ...modified."
-  else
-    echo " -     ...unchanged."
-  fi
-}
+   file_changed() {
+     local file="$1"
+     local old_md5="$2"
+     local new_md5=$( md5 "$file" )
 
-resize_vendor() {
-  local dm_block=$(df -k | cat | grep "/vendor" | cut -d' ' -f1)
+     if [ $new_md5 != $old_md5 ]; then
+       echo " -     ...modified."
+     else
+       echo " -     ...unchanged."
+     fi
+   }
 
-  echo " - Unmounting /vendor..."
-  umount /vendor
-  echo " - Checking vendor block partition before resizing..."
-  e2fsck -f $dm_block
-  echo " - Resizing the filesystem on $dm_block..."
-  resize2fs $dm_block
-  echo " - Make the partition R/W by unsharing its blocks..."
-  e2fsck -E unshare_blocks $dm_block
-  echo " - Remounting /vendor..."
-  mount /vendor
-  mount -o remount,rw /vendor
-}
+   rm_from_manifest() {
+     local service=$1
+     local md5
+     local i
 
-vendor_free_size_check() {
-  echo " - Checking vendor free size..."
-  if dd if=/dev/zero of=/vendor/test bs=1 count=1 2>/dev/null; then
-    echo " -     ...succeeded."
-    rm -f /vendor/test
-  else
-    echo " -     ...No free space left on vendor, attempting to resize vendor..."
-    echo " "
-    rm -f /vendor/test
-    resize_vendor
-  fi
-}
+     # Package path is different on Android 10. Check and adapt.
 
-disable_fbe() {
-  local md5
-  local i
-  fstab_files=`grep -lr 'fileencryption' vendor/etc`
+     [ $major -gt 9 ] && local path_extra='\.hardware'
 
-  #
-  # Exynos devices = fstab.exynos*.
-  # MediaTek devices = fstab.mt*.
-  # Snapdragon devices = fstab.qcom, fstab.emmc, fstab.default
-  #
-  for i in $fstab_files; do
-    if [ -f $i ]; then
-      echo " - Disabling file-based encryption (FBE) for /data..."
-      echo " -   Found $i."
-      md5=$( md5 $i )
-      # This comments out the offending line and adds an edited one.
-      sed -i -e 's/^\([^#].*\)fileencryption=[^,]*\(.*\)$/# &\n\1encryptable\2/g' $i
-      file_changed $i $md5
-    fi
-  done
-}
+     for i in /vendor/etc/vintf/manifest.xml \
+   	   $ANDROID_ROOT/system/etc/vintf/compatibility_matrix.device.xml \
+   	   /vendor/etc/vintf/manifest/vaultkeeper_manifest.xml; do
+       if [ -f $i ]; then
+         echo " -   Found $i."
+         md5=$( md5 $i )
+         sed -i -e '/<hal format="hidl">/{N;/<name>vendor\.samsung'"$path_extra"'\.security\.'"$service"'<\/name>/{:loop;N;/<\/hal>/!bloop;d}}' $i
+         file_changed $i $md5
+       fi
+     done
+   }
 
-disable_fde() {
-  local md5
-  local i
-  fstab_files=`grep -lr 'forceencrypt' vendor/etc`
+   disable_fbe() {
+     local md5
+     local i
 
-  #
-  # Exynos devices = fstab.exynos*.
-  # MediaTek devices = fstab.mt*.
-  # Snapdragon devices = fstab.qcom, fstab.emmc, fstab.default
-  #
-  for i in $fstab_files; do
-    if [ -f $i ]; then
-      echo " - Disabling full-disk encryption (FDE) for /data..."
-      echo " -   Found $i."
-      md5=$( md5 $i )
-      # This comments out the offending line and adds an edited one.
-      sed -i -e 's/^\([^#].*\)forceencrypt=[^,]*\(.*\)$/# &\n\1encryptable\2/g' $i
-      file_changed $i $md5
-    fi
-  done
-}
+     echo " - Disabling file-based encryption (FBE) for /data..."
 
-disable_recovery_restoration() {
-  local r=recovery-from-boot.p
-  local found
-  local i
+     # Exynos devices = fstab.exynos????
+     # Qualcomm devices = fstab.qcom
 
-  echo " - Disabling restoration of stock recovery..."
+     for i in /vendor/etc/fstab.exynos* \
+   	   /vendor/etc/fstab.qcom*; do
+       if [ -f $i ]; then
+         echo " -   Found $i."
+         md5=$( md5 $i )
+         # This comments out the offending line and adds an edited one.
+         sed -i -e 's/^\([^#].*\)fileencryption=[^,]*\(.*\)$/# &\n\1encryptable\2/g' $i
+         file_changed $i $md5
+       fi
+     done
+   }
 
-  for i in $ANDROID_ROOT $ANDROID_ROOT/system /vendor; do
-    if [ -f $i/$r~ ]; then
-	echo " -   ...already disabled."
-	found=true
-	break
-    fi
+   disable_vaultkeeper() {
+     local md5
+     local i
 
-    if [ -f $i/$r ]; then
-      echo " -   Found $i/$r. Disabling..."
-      mv $i/$r $i/$r~
+     echo " - Disabling vaultkeeperd..."
 
-      if [ -f $i/$r~ ]; then
-	echo " -     ...succeeded."
-      else
-	echo " -     ...failed."
-      fi
+     if [ $major -gt 9 ]; then
+       # This is Android 10/11: Vaultkeeper has its own init files.
+       #
+       for i in $ANDROID_ROOT/system/etc/init/vk*.rc /vendor/etc/init/vk*.rc /vendor/etc/init/vaultkeeper*; do
+         if [ -f $i ]; then
+         echo " -   Found $i."
+         md5=$( md5 $i )
+         sed -i -e 's/^[^#].*$/# &/' $i
+         file_changed $i $md5
+         fi
+       done
+     else
+       # This is Android 9: Vaultkeeper is started from init.rc.
+       #
+       sed -i -e 's/^[^#].*vaultkeeper.*$/# &/' \
+   	-re '/\/system\/bin\/vaultkeeperd/,/^#?$/s/^[^#]*$/#&/' $ANDROID_ROOT/init.rc
+     fi
 
-      found=true
-      break
-    fi
+     # Qualcomm devices such as the T860 and T865 need this, otherwise the log
+     # will be spammed with messages about failed connections to the Vaultkeeper
+     # service.
+     #
+     rm_from_manifest vaultkeeper
 
-  done
+     for i in $ANDROID_ROOT/system /vendor; do
+       if [ -f $i/bin/vaultkeeperd ]; then
+         echo " -   Found $i/bin/vaultkeeperd. Disabling..."
+         chmod 0 $i/bin/vaultkeeperd
+       fi
+     done
+   }
 
-  [ -z "$found" ] && echo " -   Found no stock recovery. Pfft."
-}
+   disable_cass() {
+     local md5
+     local i
 
-echo " "
-echo "Multi-disabler v3.1 for Samsung devices"
-echo "running Android 9 or later."
-echo "by Ian Macdonald, enhanced by afaneh92"
-echo " "
+     # The T860 needs this. Otherwise, the log will fill with messages like this:
+     #
+     # 10-20 03:23:20.501 27757 27757 E CASS: Failed to connect(4)
+     # 10-20 03:23:20.501 27757 27757 E CASS: Failed to connect ril daemon(2). Retry cnt(6)
+     # The F907B on Android 10 also needs it:
+     #
+     # 04-05 22:21:23.519  3599  3599 E CASS_DEBUG: VaultKeeper is not ready. try again.
+     # 04-05 22:21:23.519  3599  3599 I CASS_DEBUG: Disconnect ril daemon
+     # 04-05 22:21:23.519  3599  3599 I CASS_DEBUG: Failed to connect ril daemon(1). Retry cnt(2)
+     #
+     # As of OneUI 2.5, other devices need it, too; even Exynos.
+     #
+     echo " - Disabling cass..."
 
-os=$(getprop ro.build.version.release)
-major=${os%%.*}
-bl=$(getprop ro.boot.bootloader)
-dp=$(getprop ro.boot.dynamic_partitions)
+     for i in $ANDROID_ROOT/init.rc /vendor/init/cass.rc /vendor/etc/init/cass.rc; do
+       if [ -f $i ]; then
+         echo " -   Found $i. Disabling..."
+         md5=$( md5 $i )
+         sed -i -e 's/^[^#].*cass.*$/# &/' -re '/\/(system|vendor)\/bin\/cass/,/^#?$/s/^[^#]*$/#&/' $i
+         file_changed $i $md5
+       fi
+     done
+   }
 
-# Firmware version starts at either 8th or 9th character, depending on length
-# of bootloader string (12 or 13).
-#
-fw=${bl:$((${#bl} - 4)):4}
+   disable_proca() {
+     local md5
+     local i
 
-# Device is first 5 characters of bootloader string.
-#
-device=${bl:0:$((${#bl} - 8))}
-mft=$(getprop ro.product.manufacturer | tr '[A-Z]' '[a-z]')
+     echo " - Disabling process authentication..."
 
-if [ "$mft" != samsung ]; then
-  echo " - Device appears not to be made by Samsung."
-  fatal=true
-elif [ -z "$device" ]; then
-  echo " - Could not determine device model."
-  fatal=true
-elif [ $major -lt 9 ]; then
-  echo " - This software is incompatible with Android $major."
-  fatal=true
-fi
-if [ -n "$fatal" ]; then
-  echo " - Installation aborted."
-  echo " "
-  exit 1
-fi
+     # G97[035]F = pa_daemon.rc on Android 9; pa_daemon_teegris.rc on Android 10.
+     # G977B, N97[05]F, A105F, A505F = pa_daemon_teegris.rc
+     # T510 + T515 = pa_daemon_kinibi.rc
+     # T860 + T865 = pa_daemon_qsee.rc
+     #
+     for i in /vendor/etc/init/pa_daemon*.rc; do
+       if [ -f $i ]; then
+         echo " -   Found $i. Disabling..."
+         sed -i -e 's/^[^#]/# &/' $i
+         file_changed $i $md5
+       fi
+     done
 
-echo " - Detected a $device device with a $fw bootloader."
-echo " - The environment appears to be Android $major."
-echo " "
+     rm_from_manifest proca
+   }
 
-echo " - Mounting $ANDROID_ROOT..."
-mount $ANDROID_ROOT 2>/dev/null
-mount -o remount,rw $ANDROID_ROOT 2>/dev/null
+   disable_wsm() {
+     echo " - Disabling wsm..."
+     rm_from_manifest wsm
+   }
 
-if ! mount | grep $ANDROID_ROOT >/dev/null; then
-  ANDROID_ROOT=/system_root
-  echo " -   Attempt failed. Mounting at $ANDROID_ROOT..."
-  mount -o rw $ANDROID_ROOT
-  if ! mount | grep $ANDROID_ROOT >/dev/null; then
-    echo " -   Even that attempt failed. Aborting..."
-    exit 2
-  fi
-fi
+   disable_recovery_restoration() {
+     local r=recovery-from-boot.p
+     local found
+     local i
 
-echo " - Mounting /vendor..."
-mount /vendor
-mount -o remount,rw /vendor
+     echo " - Disabling restoration of stock recovery..."
 
-if ! mount | grep /vendor >/dev/null; then
-  echo " -   Mount failed. Aborting..."
-  exit 3
-fi
+     for i in $ANDROID_ROOT $ANDROID_ROOT/system; do
+       if [ -f $i/$r~ ]; then
+        echo " -   ...already disabled."
+        found=true
+        break
+       fi
 
-vendor_free_size_check
-disable_fbe
-disable_fde
-disable_recovery_restoration
+       if [ -f $i/$r ]; then
+         echo " -   Found $i/$r. Disabling..."
+         mv $i/$r $i/$r~
 
-echo " - Unmounting /vendor..."
-umount /vendor
-echo " - Unmounting $ANDROID_ROOT..."
-umount $ANDROID_ROOT
+         if [ -f $i/$r~ ]; then
+           echo " -     ...succeeded."
+         else
+           echo " -     ...failed."
+         fi
 
-echo " "
-echo " - Finished."
-echo " "
+         found=true
+         break
+       fi
 
+     done
+
+     [ -z "$found" ] && echo " -   Found no stock recovery. Pfft."
+   }
+
+   patch_libbluetooth() {
+     [ $major -ne 10 ] && return
+
+     local f=$ANDROID_ROOT/system/lib64/libbluetooth.so
+     local tf=/tmp/f
+
+     echo " - Bluetooth fix requested via renamed zip."
+     echo " - Attempting to patch $f..."
+     echo "     This may take a while."
+
+     if echo $device | grep -E '[GN]9[67][03567][UW0]|F90(0[FN]|7[BN])|T86[05]' >/dev/null; then
+       # Snapdragon based devices, such as Tab S6, Fold (5G), USA and Chinese S9/10/N9/10.
+       substitute='s/88000054691180522925c81a69000037e0030032/04000014691180522925c81a69000037e0031f2a/'
+     else
+       substitute='s/c8000034f4031f2af3031f2ae8030032/1f2003d5f4031f2af3031f2ae8031f2a/'
+     fi
+
+     xxd -p $f | tr -d '\n ' | sed -e $substitute | xxd -rp > $tf
+
+     if ! cmp $tf $f >/dev/null && [ $(stat -c '%s' $tf) -eq $(stat -c '%s' $f) ]; then
+       echo " -   Patching succeeded."
+       touch -r $f $tf
+       chmod 644 $tf
+       mv $tf $f
+     else
+       echo " -   Patching failed. No change made."
+       rm -f $tf
+     fi
+   }
+
+   if [ -z "$1" ]; then
+      help_screen;
+   fi
+
+   echo " "
+   echo "Multi-disabler v3.1 for Samsung devices"
+   echo "running Android 9 or later."
+   echo "by Ian Macdonald"
+   echo " "
+
+   os=$(getprop ro.build.version.release)
+   major=${os%%.*}
+   bl=$(getprop ro.boot.bootloader)
+   dp=$(getprop ro.boot.dynamic_partitions)
+
+   # Firmware version starts at either 8th or 9th character, depending on length
+   # of bootloader string (12 or 13).
+   #
+   fw=${bl:$((${#bl} - 4)):4}
+
+   # Device is first 5 characters of bootloader string.
+   #
+   device=${bl:0:$((${#bl} - 8))}
+   mft=$(getprop ro.product.manufacturer | tr '[A-Z]' '[a-z]')
+
+   if [ "$mft" != samsung ]; then
+     echo " - Device appears not to be made by Samsung."
+     fatal=true
+   elif [ -z "$device" ]; then
+     echo " - Could not determine device model."
+     fatal=true
+   elif [ $major -lt 9 ]; then
+     echo " - This script is incompatible with Android $major."
+     fatal=true
+   fi
+   if [ -n "$fatal" ]; then
+     echo " - Installation aborted."
+     echo " "
+     exit 1
+   fi
+
+   echo " - Detected a $device device with a $fw bootloader."
+   echo " - The environment appears to be Android $major."
+   echo " "
+
+   echo " - Mounting $ANDROID_ROOT..."
+   mount $ANDROID_ROOT 2>/dev/null
+   mount -o remount,rw $ANDROID_ROOT 2>/dev/null
+
+   if ! mount | grep $ANDROID_ROOT >/dev/null; then
+     ANDROID_ROOT=/system_root
+     echo " -   Attempt failed. Mounting at $ANDROID_ROOT..."
+     mount -o rw $ANDROID_ROOT
+     if ! mount | grep $ANDROID_ROOT >/dev/null; then
+       echo " -   Even that attempt failed. Aborting..."
+       exit 2
+     fi
+   fi
+
+   echo " - Mounting /vendor..."
+   mount /vendor
+   mount -o remount,rw /vendor
+
+   if ! mount | grep /vendor >/dev/null; then
+     echo " -   Mount failed. Aborting..."
+     exit 3
+   fi
+
+   if [ "$@" == "--disable-fbe" ] || [ "$@" == "--all" ]; then disable_fbe; fi
+   if [ "$@" == "--disable-stockrec-override" ] || [ "$@" == "--all" ]; then disable_recovery_restoration; fi
+
+   if [ "$dp" != true ]; then
+     if [ "$@" == "--disable-vaultkeeper" ] || [ "$@" == "--all" ]; then disable_vaultkeeper; fi
+     if [ "$@" == "--disable-proca" ] || [ "$@" == "--all"  ]; then disable_proca; fi
+     if [ "$@" == "--patch-bluetooth-lib" ] && [ $major -gt 9 ]; then patch_libbluetooth; fi
+   fi
+
+   if [ $major -gt 9 ]; then
+     if [ "$@" == "--disable-wsm" ] || [ "$@" == "--all" ]; then disable_wsm; fi
+     if echo $device | grep -E 'G97([035][FNUW0]|7[BNUW])|N97([05][FNUW0]|6[BNQ0]|1N)|T860|F90(0[FN]|7[BN])|M[23]15F' >/dev/null; then
+       if [ "$@" == "--disable-cass" ] || [ "@" == "--all" ]; then disable_cass; fi
+     fi
+   fi
+
+   echo " - Unmounting /vendor..."
+   umount /vendor
+   echo " - Unmounting $ANDROID_ROOT..."
+   umount $ANDROID_ROOT
+
+   echo " "
+   echo " - Finished."
+   echo " "
